server:
  port: 8081

  error:
    whitelabel:
      enabled: false

spring:
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

        type: trace
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: postgresql
  datasource:
    hikari:
      maxLifetime: 600000
    url: jdbc:postgresql://localhost:5436/localizationdb #${ENGINE_DB_URL}
    username: postgres #${DB_USER_NAME}
    password: postgres #${DB_USER_PASS}
  flyway:
    locations: classpath:db.migration
    baseline-on-migrate: true
    flyway:
      ignore-future-migrations: false


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/my-realm/protocol/openid-connect/certs

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: rabbit

  messages:
    basename: messages/messages

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 10MB

  mvc:
    path:
       match:
         matching-strategy: ant-path-matcher
  jackson:
    serialization:
      fail-on-empty-beans: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://localhost:7070/eureka/


management:
  health:
    circuit-breakers:
      enabled: true
    rate-limiters:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

  # Micrometer related properties
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans


resilience4j:circuitbreaker:
  instances:
    detailsForCustomerSupportApp:
      minimum-number-of-calls: 5
      failure-rate-threshold: 5
      wait-duration-in-open-state: 3000
      permitted-number-of-calls-in-half-open-state: 2
  configs:
    default:
      register-health-indicator:


resilience4j.rate-limiter:
  instances:
    sayHello:
      limit-for-period: 1
      limit-refresh-period: 1s
      timeout-duration: 0
      register-health-indicator: true
      event-consumer-buffer-size: 1


# traceID and spanId are predefined MDC keys - we want the logs to include them
logging:
  level:
    org.springframework.web: DEBUG
  pattern:
    level: 5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

