server:
  port: 8083

  error:
    whitelabel:
      enabled: false

spring:
  messages:
    basename: messages/messages

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 10MB

  mvc:
    path:
       match:
         matching-strategy: ant-path-matcher
  jackson:
    serialization:
      fail-on-empty-beans: false
 # config:
   # activate:
     # on-profile:
       # active: dev
path:
  dirname: ${user.home}/logoBoutiques/


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://localhost:7070/eureka/





